services:
  django:
    container_name: django
    build: ./requirements/django/
    expose:
      - "8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./requirements/django/app:/code
    networks:
      transcendence:
        aliases:
          - django
    restart: on-failure

  db:
    container_name: postgres
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - transcendence
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    restart: on-failure

  nginx:
    container_name: nginx
    ports:
          - "443:443"
    networks:
      transcendence:
        aliases:
          - nginx
    depends_on:
      - django
    build:
            context: requirements/nginx
            dockerfile: Dockerfile
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - transcendence
    restart: on-failure

volumes:
  postgres_data:

networks:
  transcendence:
    driver: bridge
