services:
  django:
    container_name: django
    build: ./requirements/django/
    expose:
      - "8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./requirements/django/app:/code
    networks:
      transcendence:
        aliases:
          - django

  db:
    container_name: postgres
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - transcendence
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      transcendence:
        aliases:
          - nginx
    depends_on:
      - django

volumes:
  postgres_data:

networks:
  transcendence:
    driver: bridge
