services:
  web:
    container_name: transcendence_web
    build: ./requirements/django/
    ports:
      - "8000:8000"
    command: ["python", "manage.py",  "runserver",  "0.0.0.0:8000"]
    volumes:
      - ./requirements/django/app:/code
    networks:
      - transcendence
    depends_on:
      - db

  db:
    container_name: transcendence_db
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - transcendence
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

networks:
  transcendence:
    driver: bridge
