# Generated by Django 5.0.6 on 2024-07-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameOver',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idBC', models.IntegerField(default=-1)),
                ('tournamentOver', models.BooleanField(default=False)),
                ('games', models.ManyToManyField(blank=True, to='website.game')),
            ],
        ),
    ]
