# Generated by Django 5.0.7 on 2024-07-15 12:48

from django.db import migrations
import os

from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
	User = apps.get_model("website", "User")
	adminName = os.getenv('SUPERUSER_ID')
	adminPsw = os.getenv('SUPERUSER_PASSWORD')
	if (User.objects.all().count() < 1):
		user = User()
		user.username = adminName
		user.password = make_password(adminPsw)
		user.is_staff = True
		user.is_superuser = True
		user.save()

class Migration(migrations.Migration):

	dependencies = [
		('website', '0005_game_winner_alter_tournament_idbc'),
	]

	operations = [
		migrations.RunPython(create_superuser)
	]
