# Generated by Django 5.0.7 on 2024-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_tournament_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ballSpeed',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bonuses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scoreToWin',
            field=models.IntegerField(default=10),
        ),
    ]
