# Generated by Django 5.0.7 on 2024-07-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_tournament_ballspeed_tournament_bonuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournamentGame',
            field=models.BooleanField(default=False),
        ),
    ]
