# Generated by Django 5.0.6 on 2024-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilPicture',
            field=models.ImageField(default='profilPicture/default.jpg', upload_to='profilPicture', verbose_name='Profil picture'),
        ),
    ]
