# Generated by Django 5.0.6 on 2024-06-17 12:07

from django.db import migrations

def create_public_room(apps, schema_editor):
	Room = apps.get_model("website", "Room")
	publicRoom = Room(publicRoom=True)
	publicRoom.save()

class Migration(migrations.Migration):

	dependencies = [
        ('website', '0001_initial'),
	]

	operations = [
		migrations.RunPython(create_public_room)
	]
