# Generated by Django 5.0.6 on 2024-06-17 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240617_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockeduser',
            name='blockedUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blocked',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='userBlocked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userBlocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='userFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userFrom', to=settings.AUTH_USER_MODEL),
        ),
    ]
