# Generated by Django 5.0.6 on 2024-06-06 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='publicRoom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
