# Generated by Django 5.0.6 on 2024-06-13 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240612_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ai', models.IntegerField()),
                ('p1Score', models.IntegerField()),
                ('p2Score', models.IntegerField()),
                ('scoreToWin', models.IntegerField()),
                ('ballSpeed', models.FloatField()),
                ('bonuses', models.BooleanField(default=True)),
                ('p1Left', models.IntegerField()),
                ('p1Right', models.IntegerField()),
                ('p2Left', models.IntegerField()),
                ('p2Right', models.IntegerField()),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
