# Generated by Django 5.0.6 on 2024-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ballSpeed',
            field=models.FloatField(default=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='p1Left',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='game',
            name='p1Right',
            field=models.IntegerField(default=68),
        ),
        migrations.AlterField(
            model_name='game',
            name='p1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2Left',
            field=models.IntegerField(default=37),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2Right',
            field=models.IntegerField(default=39),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='scoreToWin',
            field=models.IntegerField(default=10),
        ),
    ]
