# Generated by Django 5.0.6 on 2024-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_game_ballspeed_alter_game_p1left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai',
            field=models.IntegerField(default=0),
        ),
    ]
