# Generated by Django 5.0.6 on 2024-06-18 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_game_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='forfeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forfeit', to=settings.AUTH_USER_MODEL),
        ),
    ]
