# Generated by Django 5.0.6 on 2024-06-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_game_forfeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameType',
            field=models.IntegerField(default=0),
        ),
    ]
