# Generated by Django 5.0.6 on 2024-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_game_gametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p2Local',
            field=models.TextField(default=''),
        ),
    ]
