# Generated by Django 5.0.6 on 2024-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_game_p2local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='p2Local',
            field=models.TextField(blank=True, default=''),
        ),
    ]
