{
 "title": "Django Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests Rate by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_method_total[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(django_http_request_duration_seconds_sum[5m]))",
     "legendFormat": "Average Request Duration"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_view_transport_method_total[5m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Database Queries Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(django_db_execute_duration_seconds_sum[5m]))",
     "legendFormat": "Database Queries Rate"
    }
   ]
  }
 ]
}