{
 "title": "Performance Memory",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total System Memory (go_memstats_sys_bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes",
     "legendFormat": "{{instance}} - Total System Memory"
    }
   ]
  },
  {
   "title": "Free Heap Memory (go_memstats_heap_idle_bytes + go_memstats_heap_released_bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes + go_memstats_heap_released_bytes",
     "legendFormat": "{{instance}} - Free Heap Memory"
    }
   ]
  },
  {
   "title": "Used Heap Memory (go_memstats_heap_alloc_bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes",
     "legendFormat": "{{instance}} - Used Heap Memory"
    }
   ]
  }
 ]
}