global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'docker-exporter'
    static_configs:
      - targets: ['docker-exporter:9100']
