{
 "title": "Grafana Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grafana_http_request_duration_seconds_count",
     "legendFormat": "Total HTTP Requests"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(grafana_http_request_duration_seconds_count[1m])",
     "legendFormat": "HTTP Requests Rate"
    }
   ]
  },
  {
   "title": "Alertings Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(grafana_alerting_alerts[1m])",
     "legendFormat": "Alertings Rate"
    }
   ]
  },
  {
   "title": "Total Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "grafana_http_request_duration_seconds_sum",
     "legendFormat": "Total Request Duration"
    }
   ]
  }
 ]
}