{
 "title": "Nginx Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active Connections" }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "Handled Connections" }
   ]
  }
 ]
}